my_list = [1, 2, 3, 4, 5]
L = [3, 6, 7]
my_list.extend(L)
print(my_list)
my_list.insert(1, 33333)
print(my_list)
my_list.reverse()
print(my_list)
my_list.append(3)
print(my_list)
my_list.remove(3)
print(my_list)
my_list.sort()
print(my_list)
my_list.clear()
print(my_list)
